create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  content text not null,
  author text not null,
  category text not null default 'General',
  created_at timestamp with time zone not null default now()
);

alter table public.quotes enable row level security;

create policy "Allow public read access"
on public.quotes
for select
to anon
using (true);

create policy "Allow public insert access"
on public.quotes
for insert
to anon
with check (true);

create policy "Allow public update access"
on public.quotes
for update
to anon
using (true)
with check (true);
