create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  content text not null,
  author text not null,
  category text not null default 'General',
  image_url text,
  view_count bigint not null default 0,
  comment_count bigint not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.quotes
add column if not exists view_count bigint not null default 0;

alter table public.quotes
add column if not exists comment_count bigint not null default 0;

alter table public.quotes enable row level security;

drop policy if exists "Allow public read access" on public.quotes;
create policy "Allow public read access"
on public.quotes
for select
to anon
using (true);

drop policy if exists "Allow public insert access" on public.quotes;
create policy "Allow public insert access"
on public.quotes
for insert
to anon
with check (true);

drop policy if exists "Allow public update access" on public.quotes;
create policy "Allow public update access"
on public.quotes
for update
to anon
using (true)
with check (true);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.quotes(id) on delete cascade,
  author text not null default 'Guest',
  content text not null,
  created_at timestamp with time zone not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Allow public comment read access" on public.comments;
create policy "Allow public comment read access"
on public.comments
for select
to anon
using (true);

drop policy if exists "Allow public comment insert access" on public.comments;
create policy "Allow public comment insert access"
on public.comments
for insert
to anon
with check (true);

create or replace function public.refresh_quote_comment_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  quote_ids bigint[];
begin
  if TG_OP = 'INSERT' then
    quote_ids := array[NEW.quote_id];
  elsif TG_OP = 'DELETE' then
    quote_ids := array[OLD.quote_id];
  else
    quote_ids := array[OLD.quote_id, NEW.quote_id];
  end if;

  update public.quotes as quote
  set comment_count = (
    select count(*)
    from public.comments as comment
    where comment.quote_id = quote.id
  )
  where quote.id = any(quote_ids);

  return coalesce(NEW, OLD);
end;
$$;

drop trigger if exists refresh_quote_comment_count_on_change on public.comments;
create trigger refresh_quote_comment_count_on_change
after insert or update or delete on public.comments
for each row
execute function public.refresh_quote_comment_count();

update public.quotes as quote
set comment_count = (
  select count(*)
  from public.comments as comment
  where comment.quote_id = quote.id
);

create table if not exists public.site_stats (
  key text primary key,
  value bigint not null default 0,
  updated_at timestamp with time zone not null default now()
);

alter table public.site_stats enable row level security;

insert into public.site_stats (key, value)
values ('site_visits', 0)
on conflict (key) do nothing;

drop policy if exists "Allow public stats read access" on public.site_stats;
create policy "Allow public stats read access"
on public.site_stats
for select
to anon
using (true);

create or replace function public.increment_site_visit()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_value bigint;
begin
  insert into public.site_stats (key, value, updated_at)
  values ('site_visits', 1, now())
  on conflict (key)
  do update set
    value = public.site_stats.value + 1,
    updated_at = now()
  returning value into new_value;

  return new_value;
end;
$$;

grant execute on function public.increment_site_visit() to anon, authenticated;

create or replace function public.increment_quote_view(quote_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_value bigint;
begin
  update public.quotes
  set view_count = view_count + 1
  where id = quote_id
  returning view_count into new_value;

  return coalesce(new_value, 0);
end;
$$;

grant execute on function public.increment_quote_view(bigint) to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('quote-images', 'quote-images', true)
on conflict (id) do nothing;

drop policy if exists "Allow public quote image read access" on storage.objects;
create policy "Allow public quote image read access"
on storage.objects
for select
to public
using (bucket_id = 'quote-images');

drop policy if exists "Allow public quote image upload access" on storage.objects;
create policy "Allow public quote image upload access"
on storage.objects
for insert
to anon
with check (bucket_id = 'quote-images');

drop policy if exists "Allow public quote image update access" on storage.objects;
create policy "Allow public quote image update access"
on storage.objects
for update
to anon
using (bucket_id = 'quote-images')
with check (bucket_id = 'quote-images');
